title: Chiranjib Mazumdar # your name (or website title) here
logo: "images/chiranjib_git.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
Techie since 2006. Eternal learner. Passionate about learning data science. <br>
This portfolio is very much a work in progress. This is not complete by any means. <br>
Please check back often to see anything new added. <br>
  
  <a href="https://www.linkedin.com/in/chiranjibmazumdar/">View My LinkedIn Profile</a> 
   
  
theme: jekyll-theme-minimal
google_analytics: G-410HC4KQ0H # your Google Analytics tracking ID here
