title: Chiranjib Mazumdar # your name (or website title) here
logo: "images/chiranjib_git.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  
  <a href="https://www.linkedin.com/in/chiranjibmazumdar/">View My LinkedIn Profile</a> <br/>
  <a href="https://www.datacamp.com/profile/chiranjibmazumdar">View My Datacamp Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
